#!/usr/bin/env python
"""Score the Board and regenerate docs/EVALUATION.md.

    python scripts/evaluate_board.py

Runs the deterministic checks against a constructed corpus with known ground
truth, then exhaustively searches the decision function's input space for any
combination that could certify something unsafe. Writes both results to
docs/EVALUATION.md so the numbers in the docs are always the numbers the code
currently produces.
"""

from __future__ import annotations

import json
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "backend"))

from notary.evaluation import evaluate

ROOT = Path(__file__).resolve().parents[1]


def pct(value: float | None) -> str:
    return "—" if value is None else f"{value * 100:.1f}%"


def render(report: dict) -> str:
    corpus = report["corpus"]
    lines: list[str] = []

    lines.append("# Evaluation\n")
    lines.append(
        "Generated by `python scripts/evaluate_board.py`. Every number here is "
        "produced by running the shipping code — nothing in this file is "
        "hand-written.\n"
    )

    lines.append("## Why this document exists\n")
    lines.append(
        "Most AI review demos assert that their classifier works. This one "
        "measures it, and publishes where it cannot be measured. A compliance "
        "gate whose accuracy is unknown is a compliance gate you cannot deploy.\n"
    )

    # ---- invariants first: the strongest result --------------------------
    lines.append("## The safety invariant (exhaustive proof)\n")
    lines.append(
        "`decide()` has a finite input space — a handful of criteria, each in "
        "one of four outcomes, crossed with check kind, severity, confidence "
        "band, and remaining revision budget. So it is not sampled, it is "
        "**enumerated completely**.\n"
    )

    safety = report["invariants"]["no_unsafe_certification"]
    budget = report["invariants"]["exhausted_budget_never_approves"]

    lines.append("| Invariant | Combinations checked | Result |")
    lines.append("|---|---:|---|")
    lines.append(
        f"| A blocking FAIL or UNCERTAIN can never yield VERIFIED "
        f"| {safety['combinations_checked']:,} "
        f"| {'**HOLDS**' if safety['holds'] else '**VIOLATED**'} |"
    )
    lines.append(
        f"| An exhausted revision budget can never yield VERIFIED "
        f"| {budget['combinations_checked']:,} "
        f"| {'**HOLDS**' if budget['holds'] else '**VIOLATED**'} |"
    )
    lines.append("")

    if safety["violations"] or budget["violations"]:
        lines.append("### Violations found\n")
        lines.append("```json")
        lines.append(json.dumps(
            {"safety": safety["violations"], "budget": budget["violations"]}, indent=2
        ))
        lines.append("```\n")
    else:
        lines.append(
            "> Across every reachable combination, there is no input on which "
            "Notary certifies an asset that a blocking criterion failed or "
            "could not resolve. This is a stronger statement than an accuracy "
            "score: it is a property of the decision function, not an estimate "
            "of its behaviour.\n"
        )

    # ---- deterministic scores --------------------------------------------
    lines.append("## Deterministic checks — measured accuracy\n")
    lines.append(
        f"Corpus of **{corpus['total']} samples**, of which "
        f"**{corpus['near_boundary']} ({corpus['boundary_fraction'] * 100:.0f}%) "
        "sit within ±10% of a decision threshold**. That concentration is "
        "deliberate: a corpus of obvious cases reports ~100% and tells you "
        "nothing, because a threshold classifier can only be wrong near its "
        "threshold.\n"
    )
    lines.append(
        "Scored with `fail` as the positive class, since a missed violation is "
        "the error with consequences. **Recall is the number that matters** — "
        "a false alarm costs one render, a miss ships a non-compliant asset.\n"
    )

    lines.append("| Criterion | n | Precision | Recall | Accuracy | F1 | Near-boundary accuracy |")
    lines.append("|---|---:|---:|---:|---:|---:|---:|")
    for name, entry in report["deterministic"].items():
        o = entry["overall"]
        nb = entry["near_boundary"]
        nb_acc = pct(nb["accuracy"]) if nb["n"] else "—"
        lines.append(
            f"| `{name}` | {o['n']} | {pct(o['precision'])} | {pct(o['recall'])} "
            f"| {pct(o['accuracy'])} | {pct(o['f1'])} | {nb_acc} |"
        )
    lines.append("")

    any_failures = any(e["failures"] for e in report["deterministic"].values())
    if any_failures:
        lines.append("### Disagreements\n")
        for name, entry in report["deterministic"].items():
            for failure in entry["failures"]:
                lines.append(
                    f"- **{name}** / `{failure['sample']}` — expected "
                    f"`{failure['expected']}`, got `{failure['observed']}`. "
                    f"{failure['note']}"
                )
        lines.append("")
    else:
        lines.append(
            "No disagreements. Every sample, including those within 2% of a "
            "threshold, was classified as its ground truth requires.\n"
        )

    lines.append(
        "These scores are high because these checks are arithmetic, not "
        "inference. That is the argument for computing what can be computed: "
        "the measured half of the rubric is not a classifier that might be "
        "wrong, it is a measurement that is reproducible by anyone holding the "
        "file.\n"
    )

    # ---- the honest gap ---------------------------------------------------
    lines.append("## What is not evaluated\n")
    ne = report["not_evaluated"]
    lines.append("The perceptual criteria are **not scored**:\n")
    for criterion in ne["perceptual_criteria"]:
        lines.append(f"- `{criterion}`")
    lines.append("")
    lines.append(f"{ne['reason']}\n")
    lines.append(f"**Consequence.** {ne['consequence']}\n")

    lines.append("### How to close this gap\n")
    lines.append(
        "1. Assemble 30–50 real generated takes spanning pass, fail, and "
        "genuinely ambiguous.\n"
        "2. Have two reviewers label each perceptual criterion independently; "
        "record inter-rater agreement, which upper-bounds any achievable "
        "score.\n"
        "3. Run the Board and compute precision and recall per criterion, plus "
        "the escalation rate.\n"
        "4. Tune the 0.55 confidence floor against the escalation rate a real "
        "team would tolerate.\n"
        "5. Publish the table, including the criteria it does badly on.\n"
    )
    lines.append(
        "The harness for steps 3–5 already exists in "
        "`backend/notary/evaluation/`. What is missing is labelled data, and "
        "inventing it would measure our own assumptions rather than the "
        "Board.\n"
    )

    lines.append("---\n")
    lines.append(
        "*Regenerate with `python scripts/evaluate_board.py`. "
        "Raw report: `docs/evaluation-report.json`.*\n"
    )

    return "\n".join(lines)


def main() -> int:
    with tempfile.TemporaryDirectory(prefix="notary-eval-") as tmp:
        report = evaluate(Path(tmp))

    docs = ROOT / "docs"
    docs.mkdir(exist_ok=True)

    (docs / "evaluation-report.json").write_text(
        json.dumps(report, indent=2, default=str), encoding="utf-8"
    )
    (docs / "EVALUATION.md").write_text(render(report), encoding="utf-8")

    safety = report["invariants"]["no_unsafe_certification"]
    budget = report["invariants"]["exhausted_budget_never_approves"]

    print(f"corpus: {report['corpus']['total']} samples "
          f"({report['corpus']['near_boundary']} near threshold)")
    print()
    for name, entry in report["deterministic"].items():
        o = entry["overall"]
        print(f"  {name:24s} n={o['n']:3d}  precision={pct(o['precision']):>7s}  "
              f"recall={pct(o['recall']):>7s}  accuracy={pct(o['accuracy']):>7s}")
    print()
    print(f"  safety invariant   : {safety['combinations_checked']:,} combinations "
          f"-> {'HOLDS' if safety['holds'] else 'VIOLATED'}")
    print(f"  budget invariant   : {budget['combinations_checked']:,} combinations "
          f"-> {'HOLDS' if budget['holds'] else 'VIOLATED'}")
    print()
    print("wrote docs/EVALUATION.md and docs/evaluation-report.json")

    return 0 if (safety["holds"] and budget["holds"]) else 1


if __name__ == "__main__":
    raise SystemExit(main())
